### PR TITLE
Updates for 0.11.2

### PR DESCRIPTION
**Pull request by pvmerlo**

### CODE REVIEW

**Comment by Bellfalasch** [comment]
Nice one =) Good and simple fix for the timezone issue, great!

However, two issues:
* html view-file references an asset that is not in this project. Consider writing inline style instead. The view should just make sure page doesn't crash, and inform user to create a RSS content. I can fix the details if the css, ids and classes are removed.
* My changes to the build.gradle file doesn't look like they are properly merged here, so this pull is overwriting some important changes.

**Comment by pvmerlo** [comment]
"/common/styles/_all.css" is not a base style that's present in all enonic projects?
And the build.gradle changes were not compiling (enonic.defaults...) so I've removed it in order to build the app.

**Comment by Bellfalasch** [comment]
I will check about that /common/-thing, but wasn't aware of it. Not sure it is from us or if it is intentional or stable enough to use.

I will check the gradle thing and get back to you. We have a new way of publishing jars to maven repos and perhaps that is now failing. It shouldn't but since it's new there might be some things we haven't tested.

**Comment by pvmerlo** [comment]
These admin assets are present on the base Enonic installation and are even referenced on the "Tools" guide on XP docs. So I think this is not a problem...
See: http://xp.readthedocs.io/en/stable/developer/admin/tools/index.html

**Comment by Bellfalasch** [comment]
We are working now internally on solving the issues with enonic.defaults. We must have it to be able to publish the changes. However as you say there is something buggy there and it won't work for you. We will fix this as soon as possible.

I will take a look at the design of the thymeleaf-page. I love the idea, but I might do something with inline style and some text/info anyway.

You don't have to do any changes to this pull request. Just give me some time to fix internal issues and get back to merging and adjusting for 0.11.1!

**Comment by pvmerlo** [comment]
Ok, thanks for the return!

**Comment by pvmerlo** [comment]
The v0.11.2 has a initial support to categories, like proposed on #6 (Using RegEx test), the author name like you said on #5, uses the content creator if no author name property is set (supporting only string for now, not an object relationship like on SuperHero Blog does with the author content-type). Also, I've added support to timezone, with basis set on "Etc/UTC" timezone (+00:00) and usable as the Database-like string, like "Europe/Oslo".

**Comment by sigdestad** [comment]
Hmm.. I assume the timezone setting is only to be used if there is no timezone info available in the data already? http://xp.readthedocs.io/en/stable/developer/schema/input-types/datetime.html

**Comment by Bellfalasch** [comment]
Hi @pvmerlo nice things.

However, I cannot find why lib-context is added to the build?
Also, any reason why not using the moment js lib from Market instead of including it manually?

I will need to do some testing in these changes and the earlier ones. Will also look at the timezone-thing, as @sigdestad says, each content type has it's own setting for timezone on their datetime-field (use or not to use) and that should be used instead of overwriting it from the RSS-content (unnecessary setting). But I will check this all out.

**Comment by pvmerlo** [comment]
I din't saw the moment lib on market. Sorry :p The context lib was added to solve #15. I'm still working on that. For now you can just remove it? Thanks :)

**Comment by Bellfalasch** [comment]
Oh ok, perhaps add that fix in another branch so we don't mix done things with half-done things.

I can remove it and take a look at switching out moment just so we don't install dependencies that could be handled through Gradle instead. But also, I need to look at the implementation around timezone in general as it might not always work. However that will be later this week.

**Comment by Bellfalasch** [comment]
Btw #15 is not planned for 1.0 but placed in a "icebox 2.0"

See https://github.com/enonic/app-rss/projects/1

**Comment by Bellfalasch** [comment]
I understand these updates are needed asap. To make things go faster, please resolve the following issues in a new pull request:
* Remove lib-context
* Remove local moment.js
* Add (and use) lib-moment from Market
* Remove setting on site/cty for timezone (always read selected content type's timezone instead)
* Evaluate if timezone moment is needed (now that timezone settings are removed)
* Test any remaining code, especially for timezone on/off in different content types

After that I will merge, tag for 0.12.0 release, publish updated jar, and update market.

**Comment by Bellfalasch** [comment]
Just taking notes on what is discussed elsewhere:

* Keep moment.js, lib in Market does not work
* Keep timezone moment
* Keep setting for timezone (add note in readme)

This will force us to release a 0.12.1 dropping the timezone setting (might be backward breaking), but at least this buys us some more time while critical fixes and features gets released asap.

I will perform this code updates.

**Comment by Bellfalasch** [comment]
Things are now shipped as 0.12.0 but this all needs a lot of more testing. This is very rushed. Timezone settings doesn't seem to validate in RSS validators. Many readers handle this, but don't count on it. A lot of more thinking and testing is needed around timezone and datetime in general in this app.

**Pull request merged**
